-- 0015_richbuild_events.sql
--
-- RichBuild v1 — discrete product events, distinct from richbuild_visits (which only
-- tracks first/last visit timestamps for D7 retention). The working-flow diagram
-- (app 워킹 플로우, §4) calls out `signup_completed` firing at guest→member conversion
-- as a named event; this table is write-only analytics from the client, same pattern
-- as richbuild_visits.

create table if not exists public.richbuild_events (
  id          bigint generated by default as identity primary key,
  visitor_id  text not null,
  event       text not null,
  created_at  timestamptz not null default now()
);

create index if not exists idx_richbuild_events_visitor on public.richbuild_events (visitor_id, created_at);

alter table public.richbuild_events enable row level security;

-- Insert-only from the client; no select policy — read via service_role for reporting.
drop policy if exists richbuild_events_insert on public.richbuild_events;
create policy richbuild_events_insert on public.richbuild_events
  for insert with check (true);
